# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_call: 
    inputs:
      TLA:
        description: 'TLA of API owners'
        type: string
        required: true

      Repo_Name:
        description: 'The Repo name of API owners'
        type: string
        required: true   


jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo-A
        uses: actions/checkout@v2
        with:
          repository: Lamintun/distributed-repo-branch-a
          path: distributed-repo-branch-a

      - name: Check Files 1
        uses: |
          ls -R

      - name: Checkout repo-base
        uses: actions/checkout@v2
        with:
          repository: Lamintun/distributed-repo-base
          path: distributed-repo-base
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Files 2
        uses: |
            ls -R
