name: CI

on:
  workflow_dispatch: 
    inputs:
      TLA:
        description: 'TLA of API owners'
        type: string
        required: true

      Repository:
        description: 'The Repo name of API owners'
        type: string
        required: true   

  workflow_call: 
    inputs:
      TLA:
        description: 'TLA of API owners'
        type: string
        required: true

      Repository:
        description: 'The Repo name of API owners'
        type: string
        required: true   


jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo-A
        uses: actions/checkout@v2
        with:
          repository: ${{inputs.Repository}}

      - name: Check Files 1
        uses: |
          ls -R

      - name: Checkout repo-base
        uses: actions/checkout@v2
        with:
          repository: Lamintun/distributed-repo-base
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Files 2
        uses: |
            ls -R
