name: CI

on:
  workflow_dispatch: 
    inputs:
      TLA:
        description: 'TLA of API owners'
        type: string
        required: true

      Repository:
        description: 'The Repo name of API owners'
        type: string
        required: true   

  workflow_call: 
    inputs:
      TLA:
        description: 'TLA of API owners'
        type: string
        required: true

      Repository:
        description: 'The Repo name of API owners'
        type: string
        required: true   

permissions:                
  contents: write           
  pull-requests: write 

jobs:
  
  Merge-Updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo-A
        uses: actions/checkout@v2
        with:
          repository: ${{inputs.Repository}}
          path: ${{inputs.Repository}}          

      - name: Check Files 1
        run:  |
          ls -R

      - name: Checkout repo-base
        uses: actions/checkout@v2
        with:
          repository: Lamintun/distributed-repo-base
          path: distributed-repo-base
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Check Files 2
        run:  |
            ls -R

      - name: Copy TLA folder from repo-A to repo-base
        run: |
          cp -r ${{ inputs.Repository }}/${{inputs.TLA}}/* distributed-repo-base/openapi_specifications/

      # - name: Configure git
      #   run: |
      #     cd distributed-repo-base
      #     git config user.name "github-actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # - name: Commit changes
      #   run: |
      #     cd distributed-repo-base
      #     git add .
      #     git commit -m "Sync TLA folder from ${{ inputs.Repository }}"

      # - name: Push changes
      #   run: |
      #     cd distributed-repo-base
      #     git push origin main
      #   env:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Commit files
        run: |
          cd distributed-repo-base
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
          git push origin main
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}        


      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
