name: CI

on:
  workflow_dispatch: 
    inputs:
      TLA:
        description: 'TLA of API owners'
        type: string
        required: true

      Repository:
        description: 'The Repo name of API owners'
        type: string
        required: true   

  workflow_call: 
    inputs:
      TLA:
        description: 'TLA of API owners'
        type: string
        required: true

      Repository:
        description: 'The Repo name of API owners'
        type: string
        required: true   

jobs:
  
  Merge-Updates:
    permissions:                
      contents: write           
      pull-requests: write 
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo-A
        uses: actions/checkout@v2
        with:
          repository: ${{inputs.Repository}}
          path: ${{inputs.Repository}}          

      - name: Check Files 1
        run:  |
          ls -R

      - name: Checkout repo-base
        uses: actions/checkout@v2
        with:
          repository: Lamintun/distributed-repo-base
          path: distributed-repo-base

      - name: Check Files 2
        run:  |
            ls -R

      - name: Copy TLA folder from repo-A to repo-base
        run: |
          cp -r ${{ inputs.Repository }}/${{inputs.TLA}}/* distributed-repo-base/openapi_specifications/

      # - name: Configure git
      #   run: |
      #     cd distributed-repo-base
      #     git config user.name "github-actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # - name: Commit changes
      #   run: |
      #     cd distributed-repo-base
      #     git add .
      #     git commit -m "Sync TLA folder from ${{ inputs.Repository }}"

      # - name: Push changes
      #   run: |
      #     cd distributed-repo-base
      #     git push origin main
      #   env:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      # git config --global user.email "github-actions[bot]@users.noreply.github.com"
      # git config --global user.name "github-actions[bot]"
      # git remote set-url origin git@github.com:Lamintun/distributed-repo-base.git

      - name: Commit and Push changes
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Create a temporary file for the SSH key
          SSH_KEY_FILE=$(mktemp)
          echo "$SSH_PRIVATE_KEY" > $SSH_KEY_FILE
          chmod 600 $SSH_KEY_FILE

          # Prepare the SSH command with the private key
          SSH_COMMAND="ssh -i $SSH_KEY_FILE -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"

          # Change to the specific directory
          cd ./distributed-repo-base

          # Stage, commit, and push changes
          git add .
          git commit -m "Commit message"
          git remote set-url origin git@github.com:Lamintun/distributed-repo-base.git
          GIT_SSH_COMMAND="$SSH_COMMAND" git push origin main

          # Clean up the SSH key file
          rm $SSH_KEY_FILE
